### ISSUE TITLE
Launcher nie uruchamia się (nic nie ma)

### ISSUE THREAD

**Issue by Adrien-234** [MPLauncher/MPLauncher#14]
Witam od niedawna Launcher nie uruchamia się a żadnego komunikatu nie ma jedynie wyskoczy jak poklikam kilka razy (Launcher jest już uruchomiony).

[16:38:21] [INFO] ---------------------------------------------------
[16:38:21] [INFO] Checking configuration files...
[16:38:22] [INFO] ---------------------------------------------------
[16:38:22] [ERROR] ------------------------------------------------
[16:38:22] [ERROR] Unhandled Thread Exception
[16:38:22] [ERROR] System.NullReferenceException: Object reference not set to an instance of an object.
   at MP_Launcher.Program.WlaczDalej()
   at MP_Launcher.Program.Main(String[] Arguments)
[16:38:22] [ERROR] System.UnhandledExceptionEventArgs
[16:38:22] [ERROR] ------------------------------------------------

**Comment by LosTigeros** [comment]
Spróbuj wejść do `%AppData%/.mplauncher/config` i usunąć plik `configuration.mpl`
